/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    Button: typeof import('./src/components/button.vue')['default']
    Expan: typeof import('./src/components/Expan.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout1: typeof import('./src/components/layout/layout1.vue')['default']
    Layout2: typeof import('./src/components/layout/layout2.vue')['default']
    Layout3: typeof import('./src/components/layout/layout3.vue')['default']
    LayoutOne: typeof import('./src/components/layout/layoutOne.vue')['default']
    LayoutThree: typeof import('./src/components/layout/layoutThree.vue')['default']
    LayoutTwo: typeof import('./src/components/layout/layoutTwo.vue')['default']
    Nav1: typeof import('./src/components/nav/Nav1.vue')['default']
    Nav2: typeof import('./src/components/nav/Nav2.vue')['default']
    Nav3: typeof import('./src/components/nav/Nav3.vue')['default']
    Nav4: typeof import('./src/components/nav/Nav4.vue')['default']
  }
}
